services:
  - type: web
    name: weather_app
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec rails s
    envVars:
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: weather_app_db
      #     property: connectionString
      - key: RAILS_MASTER_KEY
        value: 1380d597f705ea99730c2379a6fa74f1
      - key: OPENWEATHER_API_KEY
        value: 9b78c8134756b6d17952ec490e1390c1